### ISSUE TITLE
Unable to use {{ trigger.date }} inside a trigger parameter string

### ISSUE THREAD

**Issue by LekhaR100** [kestra-io/plugin-fs#135] opened 2024-06-13 13:45 UTC
### Expected Behavior

I want to set a trigger to ingest a unique url every 15 minutes. I would like one portion of the url to change for each ingestion, depending on the time of the trigger. This portion is formatted as so: 'yyyyMMddHHmm' I cannot use now(), because occasionally it runs a minute late, causing the url portion to end with 16 instead of 15, which does not exist. The ideal solution is to replace {{ now() }} with {{ trigger.date }} so that the url format will always represent a 15 minute interval. 

### Actual Behaviour

I get this error when I attempt to use {{ trigger.date }} instead of {{ now() }}:

"Evaluate Failed with error 'Missing variable: 'date' on '[http://...{{](http://data.gdeltproject.org/gdeltv2/%7B%7B) trigger.date | date('yyyyMMddHHmm') }}00.CSV.zip' at line 1'"

### Steps To Reproduce

1. Begin creating a flow with a trigger in the kestra editor 
2. Make one of the inputs a url
3. In the trigger, take a url as an input parameter.
4. Use {{ trigger.date }} as a variable in the url
5. Execute the flow and watch the logs in kestra for an error/success

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

<img width="741" alt="Screenshot 2024-06-13 at 9 42 05 AM" src="https://github.com/kestra-io/plugin-fs/assets/171082150/bac6c88b-5621-40cf-94d4-e90fcdfe935d">

**Comment by anna-geller** [comment] 2024-06-17 10:41
duplicate of https://github.com/kestra-io/kestra/issues/4023

**Closed by anna-geller** 2024-06-17 10:41 UTC
Labels: bug
